import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, AtSign, BrainCircuit, Check, Cloud, Code2, Database, Download, ExternalLink, Globe, Mail, Menu, Network, Phone, X, Zap } from 'lucide-react'
import './styles.css'

const resumeFile = '/Prashant_Kalambe_Resume_System_Design.pdf'
const experience = [
  { period: 'Jun 2026 — Present', company: 'Cyient', role: 'Senior Full Stack Developer', project: 'John Deere · BM E-commerce Platform', tech: 'Java · Spring Boot · AWS · MySQL · React.js · Spring AI', summary: 'Leading full-stack development for catalog, cart, and checkout experiences across a cloud-native commerce platform.', points: ['Designing scalable REST APIs and MySQL data models from business requirements.', 'Building reusable React interfaces integrated with Spring Boot services.', 'Exploring Spring AI and GenAI for intelligent product recommendations.'] },
  { period: 'Apr 2024 — Jun 2026', company: 'Tata Consultancy Services', role: 'System Engineer', project: 'Stellantis · Dealer Service Data Integration', tech: 'Java · Spring Boot · AWS · MySQL · React.js · Spring AI', summary: 'Built the event-driven integration layer that moves dealer service data reliably through enterprise systems.', points: ['Built AWS pipelines with Lambda, API Gateway, RDS, SNS, and SQS.', 'Designed for high availability, scalable processing, and reduced latency.', 'Implemented JUnit 5 and Mockito automation, achieving 80%+ test coverage.'] },
  { period: 'Apr 2021 — Apr 2024', company: 'Tata Consultancy Services', role: 'System Engineer', project: 'Stellantis · Global Service Delivery Platform', tech: 'Java · Spring Boot · AWS · React.js · MySQL · Jenkins', summary: 'Delivered reliable APIs and frontend workflows for business-critical global operations.', points: ['Built REST APIs and React.js components for enterprise workflows.', 'Optimized code and database queries to improve performance by approximately 30%.', 'Implemented Jenkins CI/CD pipelines for dependable releases.'] },
]
const skills = [
  { icon: Code2, label: 'Development', items: ['Java', 'Spring Boot', 'Microservices', 'React.js', 'Node.js', 'REST APIs'] },
  { icon: Network, label: 'System design', items: ['High availability', 'Low latency', 'API design', 'Data modeling', 'Event-driven systems'] },
  { icon: Cloud, label: 'Cloud', items: ['AWS', 'Lambda', 'API Gateway', 'S3', 'RDS', 'DynamoDB', 'ECS', 'EKS'] },
  { icon: BrainCircuit, label: 'AI / GenAI', items: ['Spring AI', 'LLM integration', 'Recommendations'] },
  { icon: Database, label: 'Data', items: ['MySQL', 'DynamoDB', 'DocumentDB'] },
]

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const closeMenu = () => setMenuOpen(false)
  return <div className="site-shell">
    <header className="topbar"><a className="wordmark" href="#top" onClick={closeMenu}><span>PK</span> / profile</a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label="Toggle navigation">{menuOpen ? <X size={20} /> : <Menu size={20} />}</button><nav className={menuOpen ? 'nav-links is-open' : 'nav-links'}><a href="#work" onClick={closeMenu}>Work</a><a href="#capabilities" onClick={closeMenu}>Capabilities</a><a href="#about" onClick={closeMenu}>About</a><a className="nav-contact" href="mailto:kalambeprashantkp@gmail.com" onClick={closeMenu}>Let's connect <ArrowUpRight size={15} /></a></nav></header>
    <main id="top">
      <section className="hero section-grid"><div className="hero-copy"><p className="eyebrow"><span className="status-dot" /> Available for ambitious builds</p><h1>Software that<br /><em>moves systems</em><br />forward.</h1><p className="hero-lede">Senior full stack developer designing dependable products at the intersection of Java, cloud architecture, and intelligent interfaces.</p><div className="hero-actions"><a className="button button-dark" href="#work">Explore my work <ArrowUpRight size={17} /></a><a className="button button-quiet" href={resumeFile} download>Download CV <Download size={16} /></a></div></div><div className="hero-visual"><div className="visual-label">01 / CURRENT FOCUS</div><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="core-node"><Zap size={28} strokeWidth={1.5} /><span>build<br />with intent</span></div><div className="signal signal-a">API <ArrowUpRight size={13} /></div><div className="signal signal-b">AI <ArrowUpRight size={13} /></div><div className="signal signal-c">AWS <ArrowUpRight size={13} /></div><div className="visual-foot"><span>Java / Spring Boot</span><span>19° 02' N, Mumbai</span></div></div></section>
      <section className="ticker"><div className="ticker-track"><span>JAVA</span><b>✦</b><span>SPRING BOOT</span><b>✦</b><span>AWS</span><b>✦</b><span>REACT.JS</span><b>✦</b><span>MICROSERVICES</span><b>✦</b><span>GENAI</span><b>✦</b><span>JAVA</span><b>✦</b><span>SPRING BOOT</span></div></section>
      <section className="intro section-grid" id="about"><div className="section-index">02 / PROFILE</div><div className="intro-content"><p className="section-kicker">The short version</p><h2>I turn complex requirements into <span>clear, scalable software.</span></h2><p>From event-driven backends to thoughtful React interfaces, I care about the whole product. My work is grounded in strong system design, practical cloud architecture, and a habit of making complicated things easier to use.</p><div className="stat-row"><div><strong>5+</strong><span>years building<br />enterprise software</span></div><div><strong>300+</strong><span>DSA problems<br />solved</span></div><div><strong>30%</strong><span>performance gain<br />delivered</span></div></div></div></section>
      <section className="work section-grid" id="work"><div className="section-index">03 / EXPERIENCE</div><div className="work-content"><div className="section-heading"><p className="section-kicker">Selected experience</p><h2>Recent chapters</h2></div>{experience.map((item, index) => <article className="experience-card" key={item.project}><div className="card-number">0{index + 1}</div><div className="card-main"><div className="card-meta"><span>{item.period}</span><span>{item.company}</span></div><h3>{item.role}</h3><h4>{item.project}</h4><p className="tech-line">{item.tech}</p><p className="card-summary">{item.summary}</p><ul>{item.points.map(point => <li key={point}><Check size={15} />{point}</li>)}</ul></div><ArrowUpRight className="card-arrow" size={20} /></article>)}</div></section>
      <section className="capabilities section-grid" id="capabilities"><div className="section-index">04 / TOOLKIT</div><div className="capabilities-content"><div className="section-heading"><p className="section-kicker">How I work</p><h2>Built for the<br /><span>real world.</span></h2></div><div className="skill-grid">{skills.map(({ icon: Icon, label, items }) => <div className="skill-block" key={label}><Icon size={20} strokeWidth={1.5} /><h3>{label}</h3><p>{items.join(' · ')}</p></div>)}</div></div></section>
      <section className="contact section-grid"><div className="section-index">05 / NEXT MOVE</div><div className="contact-content"><p className="section-kicker">Have a hard problem?</p><h2>Let's make it<br /><em>work beautifully.</em></h2><a className="email-link" href="mailto:kalambeprashantkp@gmail.com">kalambeprashantkp@gmail.com <ArrowUpRight size={22} /></a></div></section>
    </main>
    <footer><span>© 2026 Prashant Kalambe</span><span>Senior Full Stack Developer</span><div className="socials"><a href="mailto:kalambeprashantkp@gmail.com" aria-label="Email"><Mail size={17} /></a><a href="https://www.linkedin.com" target="_blank" rel="noreferrer" aria-label="LinkedIn"><AtSign size={17} /></a><a href="https://github.com" target="_blank" rel="noreferrer" aria-label="GitHub"><Globe size={17} /></a><a href="tel:+918459747041" aria-label="Phone"><Phone size={17} /></a></div></footer>
  </div>
}
export default App

createRoot(document.getElementById('root')).render(<App />)
